### ISSUE TITLE
formatador apagando comentários

### ISSUE THREAD

**Issue by rafaelgavarron** [DesignLiquido/visualg#10]
quando habilito a opção "format on save", toda vez que salvo apaga um caractere dos comentários e também apaga o "L" do escreval

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/visualg/releases/tag/0.1.6. Favor aguardar lançamento da versão 0.12.2 da extensão para realizar testes.
