### ISSUE TITLE
Quebra de linha automática na saída  

### ISSUE THREAD

**Issue by murilosanches2** [DesignLiquido/visualg#14]
algoritmo "Torneio Futebol"
var
    times: vetor[1..3] de caracter
    c: inteiro
inicio
    escreval("------------------------------")
    escreval("  CAMPEONATO DE FUTEBOL")
    escreval("------------------------------")
fimalgoritmo

Na hora de executar, está descendo pra linha de baixo, mesmo tendo espaço para continuar

![Screenshot_1](https://github.com/DesignLiquido/visualg/assets/104803956/3f539707-ac9d-4bf1-82ff-9978e81ee59e)

**Comment by Aristidescosta** [comment]
@murilosanches2 Poderia verificar a versão que estás a utilizar??

# Versão
`v0.12.15`

# Exemplo
```
algoritmo "Torneio Futebol"
var
times: vetor[1..3] de caracter
c: inteiro
inicio
escreval("------------------------------")
escreval(" CAMPEONATO DE FUTEBOL")
escreval("------------------------------")
fimalgoritmo
```

# Resultado
![image](https://github.com/DesignLiquido/visualg/assets/69801513/7088538f-2ec4-4395-a722-0f56819451a0)

**Comment by murilosanches2** [comment]
0.12.15

**Comment by murilosanches2** [comment]
Agora voltou ao normal kkkkk estranho

**Comment by leonelsanchesdasilva** [comment]
Estou considerando este problema como corrigido na versão 0.12.15.
