### ISSUE TITLE
Código em loop usando "enquanto"

### ISSUE THREAD

**Issue by fernandofcursos** [DesignLiquido/visualg#6]
Ao usar a extensão no VSCode o código fica em loop infinito, tendo que fechar o VSCode, quando criei o código com a instrução enquanto. Testei direto no Visualg, em ambiente windows e funciona. Estou usando o VSCode em Mac, com SO Monterrey.

algoritmo "atividade_enquanto_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Desenvolva um algoritmo que pe�a um valor ao usuário
// e só feche quando o usuário digitar o valor 0.

// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/02/2024
var
   // Seção de Declaracões das variáveis
   x:real

inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   x:=1
   enquanto x<>0 faca
      escreval("Digite um número")
      leia(x)
   fimenquanto

fimalgoritmo

**Comment by leonelsanchesdasilva** [comment]
@fernandofcursos Obrigado por reportar. Estou trabalhando na correção. Te aviso por aqui.

**Comment by fernandofcursos** [comment]
Ok

Em qui., 29 de fev. de 2024 às 16:55, Leonel Sanches da Silva <
***@***.***> escreveu:

**Comment by leonelsanchesdasilva** [comment]
@fernandofcursos O problema foi resolvido na versão 0.10.14 da extensão. Só atualizar ela por dentro do VSCode.

**Comment by fernandofcursos** [comment]
Obrigado!

Em dom., 3 de mar. de 2024 09:41, Leonel Sanches da Silva <
***@***.***> escreveu:
