### ISSUE TITLE
Bugs no Debug Console

### ISSUE THREAD

**Issue by joaopedrofrech** [DesignLiquido/visualg#8]
Venho encontrando algumas diferenças no output no console de depuração comparado ao terminal do Visualg. Pelo vscode o comando escreva("O valor de x é ", x:10:1, "e o valor de y é ", y) não tem o output esperado, o espaçamento vai depois do valor de x e o mesmo não filtra as casa decimais.

Ao utilizar um loop "para ate faca"o debug console simplesmente não funciona, nada acontece.

Comecei a utilizar o plugin a apenas 1 dia, vou reportando mais problemas durante o uso neste tópico.

No momento o uso da extensão está sendo inviável, estou recomendo ao uso de VM.

![bugs-1](https://github.com/DesignLiquido/visualg/assets/36735138/faca94e6-a145-44e5-ae9b-feccf3e9a280)
![bugs-2](https://github.com/DesignLiquido/visualg/assets/36735138/0a7800c6-dc25-45ee-880d-cf227557c0a0)
![bugs-3](https://github.com/DesignLiquido/visualg/assets/36735138/69bfe353-4baf-4dc9-9c4a-4e121ce9f49d)

**Comment by leonelsanchesdasilva** [comment]
```portugol
algoritmo "X SOMA"
var
    x, SOMA: inteiro
inicio
    x <- 0
    SOMA <- 0

    para x de 1 ate 6 faca
        SOMA <- x + 1
    fimpara

    escreval("x: ", x:10:1, "  SOMA:", soma)
fimalgoritmo
```

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/visualg/commit/29a681456d49a43fe5eba9ce156ec2491ff4d3e1. Se julgar necessário, após o lançamento de nova versão da extensão, favor abrir outro ticket.
