### ISSUE TITLE
Problema de escopo na repetição do valor de variavel

### ISSUE THREAD

**Issue by Aristidescosta** [DesignLiquido/visualg#9]
Ao executar o código a seguir, observei um comportamento inesperado na saída. O código deveria mostrar a contagem de 1 a 6 duas vezes, mas ele está mostrando apenas uma contagem de 1 a 6.

```
algoritmo "valor x"
var
    x: inteiro
inicio
    x <- 0

    para x de 1 ate 6 faca
        escreval(x)
    fimpara

    para x de 1 ate 6 faca
        escreval(x)
    fimpara
fimalgoritmo
```

## Comportamento Esperado:
![image](https://github.com/DesignLiquido/visualg/assets/69801513/85847b06-ca48-490d-9b4f-91b3e3f8ec74)

## Comportamento Atual (Execução Normal):
![image](https://github.com/DesignLiquido/visualg/assets/69801513/62467289-b05d-4254-9980-f9173e810af7)

## Comportamento Atual (Depuração):
![image](https://github.com/DesignLiquido/visualg/assets/69801513/676fe0e3-410f-45b5-b0d4-ab1f7134185b)

## Possível Causa:
O problema pode estar relacionado ao escopo da variável `x` nos loops. Durante a execução normal, a variável `x` não está sendo reiniciada para 1 no segundo loop, resultando na contagem ser exibida apenas uma vez.

## Observações Adicionais:

Durante a depuração, ao observar o valor de `x`, nota-se que ele é reiniciado para 1 no segundo loop.
Esse comportamento indica que o código está funcionando corretamente durante a depuração, mas não na execução normal.

**Comment by leonelsanchesdasilva** [comment]
Consegui simular exatamente o contrário: a execução normal faz os dois loops corretos. A execução com depuração faz apenas um.

**Comment by leonelsanchesdasilva** [comment]
Resolvido em https://github.com/DesignLiquido/visualg/releases/tag/0.0.5.
